name: Update and Deploy
on:
  push:
    branches: main
    paths:
      - src/**
  pull_request:
    branches: main
    paths:
      - src/**

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update version and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.VSEPLET_GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          deno run --allow-all --unstable-broadcast-channel --unstable-kv ./update-semver-deploy-jsr.workflow.ts

      # - name: Publish
      #   run: npx jsr publish --allow-slow-types